-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "availableEquity" DECIMAL(65,30),
ADD COLUMN     "currentValue" DECIMAL(65,30),
ADD COLUMN     "lastPaymentDate" TIMESTAMP(3),
ADD COLUMN     "lastValueUpdate" TIMESTAMP(3),
ADD COLUMN     "lenderName" TEXT,
ADD COLUMN     "loanNumber" TEXT,
ADD COLUMN     "missedPayments" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mortgageBalance" DECIMAL(65,30),
ADD COLUMN     "mortgagePaymentStatus" TEXT,
ADD COLUMN     "mortgageRate" DOUBLE PRECISION,
ADD COLUMN     "mortgageStartDate" TIMESTAMP(3),
ADD COLUMN     "mortgageTerm" INTEGER,
ADD COLUMN     "nextPaymentDue" TIMESTAMP(3),
ADD COLUMN     "plaidAccessToken" TEXT,
ADD COLUMN     "plaidAccountId" TEXT,
ADD COLUMN     "plaidItemId" TEXT,
ADD COLUMN     "plaidLastSync" TIMESTAMP(3),
ADD COLUMN     "plaidLinked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "refiRecommendation" TEXT,
ADD COLUMN     "shouldConsiderRefi" BOOLEAN NOT NULL DEFAULT false;
